baseURL = 'https://capysecurity.com/'
languageCode = 'en-us'
title = 'Audacious Blog'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Resume'
pageRef = '/resume'
weight = 30

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 40

[module]
  [module.hugoVersion]
    extended = true
    min = "0.116.0"
